@PriceList.Api_HostAddress = https://localhost:7034

GET {{PriceList.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{PriceList.Api_HostAddress}}/api/form
Content-Type: application/json

{
  //FormCreateDto
}

###

@search=string
GET {{PriceList.Api_HostAddress}}/api/category?search={{search}}

###

@id=0
GET {{PriceList.Api_HostAddress}}/api/brand/{id:int}?id={{id}}

###

GET {{PriceList.Api_HostAddress}}/api/p
roductgroup

###
